import type { QuestionRecord } from '@/types';

export const sampleQuestions: QuestionRecord[] = [
  {
    id: 'q-wz7-place-value-1',
    prompt: 'What is the value of the digit 5 in 3,582?',
    answer: '500',
    wzLevel: 'WZ7',
    domain: 'Number and Place Value',
    skill: 'place value to thousands',
    michiganStandard: '3.NBT.A.1',
    kumonReference: 'A 170',
    difficulty: 3,
    status: 'approved',
    commonErrors: ['Choosing 50 instead of 500'],
    hints: ['Read the place from right to left: ones, tens, hundreds, thousands.'],
    teacherExplanation: 'The digit 5 is in the hundreds place, so its value is 500.',
  },
  {
    id: 'q-wz8-multiplication-1',
    prompt: 'Solve 24 × 6.',
    answer: '144',
    wzLevel: 'WZ8',
    domain: 'Operations and Fluency',
    skill: 'multi-digit multiplication',
    michiganStandard: '4.NBT.B.5',
    kumonReference: 'D 90',
    difficulty: 4,
    status: 'approved',
    commonErrors: ['Forgetting to regroup'],
    hints: ['Break 24 into 20 and 4.'],
    teacherExplanation: '24 × 6 = (20 × 6) + (4 × 6) = 120 + 24 = 144.',
  },
  {
    id: 'q-wz9-fraction-1',
    prompt: 'What is 3/4 + 1/8?',
    answer: '7/8',
    wzLevel: 'WZ9',
    domain: 'Fractions, Decimals, Measurement, and Ratio',
    skill: 'add fractions with unlike denominators',
    michiganStandard: '5.NF.A.1',
    kumonReference: 'E 120',
    difficulty: 5,
    status: 'approved',
    commonErrors: ['Adding tops and bottoms directly'],
    hints: ['Change 3/4 into eighths first.'],
    teacherExplanation: '3/4 = 6/8, and 6/8 + 1/8 = 7/8.',
  },
  {
    id: 'q-wz10-geometry-1',
    prompt: 'A rectangle has length 9 and width 4. What is its area?',
    answer: '36',
    wzLevel: 'WZ10',
    domain: 'Geometry, Data, and Word Problems',
    skill: 'area of rectangles',
    michiganStandard: '4.MD.A.3',
    kumonReference: 'C 160',
    difficulty: 3,
    status: 'approved',
    commonErrors: ['Adding instead of multiplying'],
    hints: ['Area means rows times columns.'],
    teacherExplanation: 'Area of a rectangle is length × width, so 9 × 4 = 36.',
  },
  {
    id: 'q-wz13-negative-1',
    prompt: 'Which number is greater, -3 or -7?',
    answer: '-3',
    wzLevel: 'WZ13',
    domain: 'Signed Numbers and Prealgebra Bridge',
    skill: 'compare signed numbers',
    michiganStandard: '6.NS.C.7',
    kumonReference: 'J 20',
    difficulty: 4,
    status: 'approved',
    commonErrors: ['Thinking -7 is greater because 7 is bigger'],
    hints: ['Use a number line.'],
    teacherExplanation: 'On a number line, -3 is to the right of -7, so -3 is greater.',
  },
  {
    id: 'q-wz14-ratio-1',
    prompt: 'If the ratio of red to blue marbles is 2:3 and there are 12 blue marbles, how many red marbles are there?',
    answer: '8',
    wzLevel: 'WZ14',
    domain: 'Signed Numbers and Prealgebra Bridge',
    skill: 'ratios and rates',
    michiganStandard: '6.RP.A.3',
    kumonReference: 'J 80',
    difficulty: 6,
    status: 'approved',
    commonErrors: ['Adding 2 and 3 then dividing incorrectly'],
    hints: ['3 parts = 12, so 1 part = 4.'],
    teacherExplanation: 'If 3 parts equal 12, then each part is 4. Red is 2 parts, so 2 × 4 = 8.',
  }
];
